### ISSUE TITLE
Issue with Java version 1.8.0_131 - IllegalStateException cannot evaluate com.sun.webkit.dom.HTMLDocumentImpl.toString()

### ISSUE THREAD

**Issue by MrBrits** [webfolderio/ui4j#101]
Good day,

I have been using ui4j for a while now without issues, but since upgrading to Java version 1.8.0_131 from 1.8.0_45 it is not working for me anymore.

When calling
`Page page = browser.navigate(url)`
with the same url I've been using for the last 2 years it fails.

The Page returns fine but the document itself is not the html string that I have been expecting
It returns with:
Method threw 'java.lang.IllegalStateException' exception. Cannot evaluate com.sun.webkit.dom.HTMLDocumentImpl.toString()
And I have no idea how to debug this situation.

Any help would be greatly appreciated.
With Java version 1.0.8_45 it works perfectly.

Just want to add that I have upgraded ui4j to the latest version and I am still facing the same issue

**Comment by malkomich** [comment]
Why was this issue closed without any response? No solution for this?
