### ISSUE TITLE
WebkitBrowser.navigate() synchronization

### ISSUE THREAD

**Issue by wwilk** [webfolderio/ui4j#65]
Why [WebkitBrowser#navigate(String)](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/main/java/com/ui4j/webkit/WebKitBrowser.java#L340) method is synchronized, while [WebkitBrowser#navigate(String, PageConfiguration)](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/main/java/com/ui4j/webkit/WebKitBrowser.java#L346) isn't? 

It may be important for concurrent access to WebkitBrowser, like in [this example](https://github.com/ui4j/ui4j/blob/master/ui4j-sample/src/main/java/com/ui4j/sample/BingSearch.java).

**Comment by ui4j** [comment]
Thanks for the bug report. Its my mistake, I am going to add synchronized keyword to [WebkitBrowser#navigate(String, PageConfiguration)](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/main/java/com/ui4j/webkit/WebKitBrowser.java#L346)

**Comment by DennyStasaskiOOP** [comment]
The synchronized keyword has not been added.  Are you still maintaining this project?
