### ISSUE TITLE
How to sniff http request being done by the page?

### ISSUE THREAD

**Issue by tomsotte** [webfolderio/ui4j#79]
How to sniff http request being done by the page?

I'll try to explain me better. When you load a page there are several http request for other files. Is there a way to have a list of those request and sniff/filter them?

EDIT: Or at least track the response received?

**Comment by asevans48** [comment]
Just curious.  Does this work? http://stackoverflow.com/questions/17574675/how-to-analyze-the-network-traffic-with-javafx.  Perhaps with an interceptor installed.

**Comment by ui4j** [comment]
You can use @asevans48 suggested solution. Ui4j already use custom HandlerFactory to intercept network traffic. Interceptor helps to read and modify the header & cookie values. Here is a sample test case [InterceptorTest.java](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/InterceptorTest.java) that use interceptor feature.
