### ISSUE TITLE
Can ui4j run in Amazon EC2?

### ISSUE THREAD

**Issue by franz-see** [webfolderio/ui4j#90]
The commands for running it headless in linux does not seem to work (or seems to be incomplete). Kindly advice how to run it in EC2.

**Comment by asevans48** [comment]
Have you tried xvfb? http://corpocrat.com/2015/08/25/screenshots-using-firefox-and-xvfb-in-amazon-ec2/. xvfb-run -a will automatically assign a screen number.

**Comment by ui4j** [comment]
Monocle version is updated. Could you please update the ui4j version to 2.2.0 and monocle to 8u76

https://github.com/ui4j/ui4j/issues/86
