### ISSUE TITLE
Missing artifact when including in Maven

### ISSUE THREAD

**Issue by Kukulcanz** [webfolderio/ui4j#96]
I'm trying to use ui4j for a project and i am including it from Maven but i keep getting an error on the including operation.

"Missing artifact com.github.ui4j.ui4j.ui4j-all:ui4j-api:bundle:2.2.0"

The group id and artifact id i used to inject the dependency are all correct and i included the repository as said in FAQ. 

Am i missing something ?

**Comment by ui4j** [comment]
Hi,

Hi new verions published to jitpack repo instead of maven central repo.

Please add jitpack repo to your pom file before using ui4j.

<repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
</repository>

**Comment by Kukulcanz** [comment]
[pom.txt](https://github.com/ui4j/ui4j/files/798654/pom.txt)

I do have that in my pom , as i said, i read the faq. I'll link it here. The error is in the first line , it says 2 artifacts are missing ; ui4j-api:bundle and ui4j-webkit.

I also have deleted the local repository and updated the project, but the error is still there.

**Comment by ui4j** [comment]
Sorry, about the repo problem. You are absolutely right. Version 2.2.0 is broken. My local m2 repo contains local build thats why i cant reproduce the problem. I am going the fix the problem. Something is wrong with jitpack.

You could use previous version from maven central before i fix the problem.

```xml
<dependency>
    <groupId>com.ui4j</groupId>
    <artifactId>ui4j-all</artifactId>
    <version>2.1.0</version>
</dependency>
```

**Comment by ui4j** [comment]
I fixed the problem.
Could you please try to update ui4j version to 2.2.2

```xml
<repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
</repository>

<dependency>
    <groupId>com.github.ui4j.ui4j</groupId>
    <artifactId>ui4j-all</artifactId>
    <version>2.2.2</version>
</dependency>
```

**Comment by webfolderio** [comment]
Maven artifacts: https://github.com/webfolderio/ui4j#integration-with-maven
